#!/usr/bin/env python3
"""Scaffold a new ArtilleryGun USTRUCT header.

Usage:
    python new_gun.py --name MyGun --module-api BRISTLE54_API [--out DIR] [--base FArtilleryGun]

Emits F<Name>.h following the FMockArtilleryGun pattern (constructor pair +
ARTGUN_MACROAUTOINIT). Fire-phase overrides are intentionally omitted so the
base FArtilleryGun ability chain runs; add them only when you need custom behavior.

After generation, add a GunDefinitions DataTable row:
    GunDefinitionId = "<Name>"   IsCPP = true
    LoadableCPP     = "/Script/<YourModule>.<Name>"   (NO F prefix)
"""
import argparse
import re
import sys
from pathlib import Path

if sys.stdout.encoding and sys.stdout.encoding.lower() != "utf-8":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

HEADER = '''// Generated by artillery-guns skill (scripts/new_gun.py). Fill out copyright as needed.

#pragma once

#include "CoreMinimal.h"
{includes}
#include "F{name}.generated.h"

'''

GUN_BODY = '''USTRUCT(BlueprintType)
struct {api} F{name} : public FArtilleryGun
{{
\tGENERATED_BODY()

public:
\tfriend class UArtilleryPerActorAbilityMinimum;

\tF{name}(const FGunKey& KeyFromDispatch, UArtilleryDispatch* Dispatch)
\t\t: FArtilleryGun(KeyFromDispatch, Dispatch)
\t{{
\t}}

\tF{name}() = default;

\tvirtual bool Initialize(
\t\tconst FGunKey& KeyFromDispatch,
\t\tconst bool MyCodeWillHandleKeys,
\t\tUArtilleryPerActorAbilityMinimum* PF = nullptr,
\t\tUArtilleryPerActorAbilityMinimum* PFC = nullptr,
\t\tUArtilleryPerActorAbilityMinimum* F = nullptr,
\t\tUArtilleryPerActorAbilityMinimum* FC = nullptr,
\t\tUArtilleryPerActorAbilityMinimum* PtF = nullptr,
\t\tUArtilleryPerActorAbilityMinimum* PtFc = nullptr,
\t\tUArtilleryPerActorAbilityMinimum* FFC = nullptr)
\t\toverride
\t{{
\t\t// Stat defaults live HERE - not in redeclared members (they SHADOW the
\t\t// base members; seeding reads the base, FArtilleryGun.cpp:107-118) and
\t\t// not in ctor bodies (the DataTable loader may default-construct).
\t\t// Initialize runs on every path; assign BEFORE the macro seeds attributes.
\t\tMaxAmmo = 30;     // 0 disables the ammo/reload system entirely
\t\tFirerate = 50;    // frames between shots, ~120hz sim
\t\tReloadTime = 120; // frames to reload
\t\treturn ARTGUN_MACROAUTOINIT(MyCodeWillHandleKeys);
\t}}
}};
'''

# Trigger guns: NO constructors. FSimpleTriggerGun declares none, and FArtilleryGun's
# (FGunKey, Dispatch) ctor is an indirect base - unreachable from a mem-initializer list.
# Canonical example: FQuestTriggerGun (Systems/FQuestGun.h), which declares no ctors.
TRIGGER_BODY = '''USTRUCT(BlueprintType)
struct {api} F{name} : public FSimpleTriggerGun
{{
\tGENERATED_BODY()

public:
\t// No constructors on purpose (see FQuestTriggerGun). Keys arrive via the inherited
\t// Initialize (ARTGUN_MACROAUTOINIT in FArtilleryGun).

\t// Trigger logic. Base PreFireGun gates on VerifiedFrame (or Inventory_VERIFIEDFRAMETESTMODE)
\t// before calling Precheck, and routes straight to PostFireGun on success -
\t// the Prefire/Fire ability phases are skipped on this path.
\tvirtual bool Precheck() override
\t{{
\t\treturn true; // TODO: your condition, e.g. MyDispatch->DoesEntityHaveTag(MyProbableOwner, Tag)
\t}}

\tfriend uint32 GetTypeHash(const F{name}& Arg)
\t{{
\t\treturn Arg.MyGunKey.GunInstanceID;
\t}}

\t// GetTypeHash/operator==/std::hash trio: the FQuestGun idiom, required if this type
\t// is ever stored BY VALUE (seq::ordered_set). Live registry paths store TSharedPtr -
\t// polymorphic, no slicing (see reference/gotchas.md section Trigger guns).
\tbool operator==(const F{name}& other) const
\t{{
\t\treturn MyGunKey == other.MyGunKey;
\t}}
}};

namespace std {{
\ttemplate <>
\tstruct hash<F{name}> {{
\t\tstd::size_t operator()(const F{name}& u) const noexcept {{
\t\t\treturn u.MyGunKey.GunInstanceID;
\t\t}}
\t}};
}}
'''

BASES = {
    "FArtilleryGun": {
        "includes": ['"CoreTypes.h"', '"FGunKey.h"', '"GameplayEffectTypes.h"',
                     '"UArtilleryAbilityMinimum.h"', '"FArtilleryGun.h"'],
        "body": GUN_BODY,
        "next": [
            'Add a GunDefinitions DataTable row:',
            '  GunDefinitionId = "{name}"  IsCPP = true',
            '  LoadableCPP     = "/Script/<YourModule>.{name}"   (NO F prefix)',
            '  (Loader reads only Id/IsCPP/LoadableCPP today; ability fields are dead.',
            '   Inject custom abilities via the Initialize params - see reference/authoring-guns.md.)',
            'Then: FCM->RegisterGun + RegisterPattern, or RequestUnboundGun (SKILL.md workflow A/B).',
        ],
    },
    "FSimpleTriggerGun": {
        "includes": ['"FArtilleryGun.h"', '"InventoryEssentialTypes.h"'],
        "body": TRIGGER_BODY,
        "next": [
            'Trigger guns are DataTable-loaded like any gun; the inventory path creates',
            'them via CreateOnVerTick -> GetGun (InventoryDispatch.cpp:129-130), stored',
            'polymorphically in GunByKey + TriggerGuns_BusyWorkerOnly (no slicing).',
            'Note: Inventory_VERIFIEDFRAMETESTMODE is currently #defined true, so Precheck',
            'runs on every activation. See reference/authoring-guns.md; example:',
            'FQuestTriggerGun (Public/Systems/FQuestGun.h).',
        ],
    },
}


def main() -> int:
    parser = argparse.ArgumentParser(description="Scaffold a new ArtilleryGun USTRUCT header.")
    parser.add_argument("--name", required=True, help="Gun name, with or without the F prefix")
    parser.add_argument("--module-api", required=True, help="Module API macro, e.g. BRISTLE54_API")
    parser.add_argument("--out", default=".", help="Output directory (default: cwd)")
    parser.add_argument("--base", default="FArtilleryGun",
                        help=f"Base struct, one of: {', '.join(sorted(BASES))}")
    args = parser.parse_args()

    # Strip the UE struct prefix only when it's actually a prefix: 'F' followed
    # by an uppercase letter (FSparkplug -> Sparkplug; FinalCheck stays FinalCheck).
    name = args.name
    if len(name) > 2 and name[0] == "F" and name[1].isupper():
        name = name[1:]
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", name):
        print(f"error: '{name}' is not a valid C++ identifier", file=sys.stderr)
        return 1
    if args.base not in BASES:
        print(f"error: base must be one of {sorted(BASES)}", file=sys.stderr)
        return 1

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / f"F{name}.h"
    if out_file.exists():
        print(f"error: {out_file} already exists - refusing to overwrite", file=sys.stderr)
        return 1

    cfg = BASES[args.base]
    includes = "\n".join(f"#include {inc}" for inc in cfg["includes"])
    text = (HEADER.format(name=name, includes=includes)
            + cfg["body"].format(name=name, api=args.module_api))
    out_file.write_text(text, encoding="utf-8")
    print(f"wrote {out_file}")
    print("\nNext:")
    for line in cfg["next"]:
        print("  " + line.format(name=name))
    return 0


if __name__ == "__main__":
    sys.exit(main())
