#!/usr/bin/env python3
"""Scaffold a new ArtilleryGun USTRUCT header.

Usage:
    python new_gun.py --name MyGun --module-api BRISTLE54_API [--out DIR] [--base FArtilleryGun]

Emits F<Name>.h following the FMockArtilleryGun pattern (constructor pair +
ARTGUN_MACROAUTOINIT). Fire-phase overrides are intentionally omitted so the
base FArtilleryGun ability chain runs; add them only when you need custom behavior.

After generation, add a GunDefinitions DataTable row:
    GunDefinitionId = "<Name>"   IsCPP = true
    LoadableCPP     = "/Script/<YourModule>.<Name>"   (NO F prefix)
"""
import argparse
import re
import sys
from pathlib import Path

HEADER_TEMPLATE = '''// Generated by artillery-guns skill (scripts/new_gun.py). Fill out copyright as needed.

#pragma once

#include "CoreMinimal.h"
#include "CoreTypes.h"
#include "FGunKey.h"
#include "GameplayEffectTypes.h"
#include "UArtilleryAbilityMinimum.h"
#include "{base}.h"
#include "F{name}.generated.h"

USTRUCT(BlueprintType)
struct {api} F{name} : public {base}
{{
\tGENERATED_BODY()

public:
\tfriend class UArtilleryPerActorAbilityMinimum;

\tF{name}(const FGunKey& KeyFromDispatch, UArtilleryDispatch* Dispatch)
\t\t: {base}(KeyFromDispatch, Dispatch)
\t{{
\t}}

\tF{name}() = default;

\tvirtual bool Initialize(
\t\tconst FGunKey& KeyFromDispatch,
\t\tconst bool MyCodeWillHandleKeys,
\t\tUArtilleryPerActorAbilityMinimum* PF = nullptr,
\t\tUArtilleryPerActorAbilityMinimum* PFC = nullptr,
\t\tUArtilleryPerActorAbilityMinimum* F = nullptr,
\t\tUArtilleryPerActorAbilityMinimum* FC = nullptr,
\t\tUArtilleryPerActorAbilityMinimum* PtF = nullptr,
\t\tUArtilleryPerActorAbilityMinimum* PtFc = nullptr,
\t\tUArtilleryPerActorAbilityMinimum* FFC = nullptr)
\t\toverride
\t{{
\t\treturn ARTGUN_MACROAUTOINIT(MyCodeWillHandleKeys);
\t}}
}};
'''

VALID_BASES = {"FArtilleryGun", "FSimpleTriggerGun"}


def main() -> int:
    parser = argparse.ArgumentParser(description="Scaffold a new ArtilleryGun USTRUCT header.")
    parser.add_argument("--name", required=True, help="Gun name, with or without the F prefix")
    parser.add_argument("--module-api", required=True, help="Module API macro, e.g. BRISTLE54_API")
    parser.add_argument("--out", default=".", help="Output directory (default: cwd)")
    parser.add_argument("--base", default="FArtilleryGun",
                        help=f"Base struct, one of: {', '.join(sorted(VALID_BASES))}")
    args = parser.parse_args()

    name = args.name[1:] if args.name.startswith("F") and len(args.name) > 1 else args.name
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", name):
        print(f"error: '{name}' is not a valid C++ identifier", file=sys.stderr)
        return 1
    if args.base not in VALID_BASES:
        print(f"error: base must be one of {sorted(VALID_BASES)}", file=sys.stderr)
        return 1

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / f"F{name}.h"
    if out_file.exists():
        print(f"error: {out_file} already exists - refusing to overwrite", file=sys.stderr)
        return 1

    out_file.write_text(HEADER_TEMPLATE.format(name=name, api=args.module_api, base=args.base))
    print(f"wrote {out_file}")
    print(f"\nNext: add a GunDefinitions DataTable row:")
    print(f'  GunDefinitionId = "{name}"  IsCPP = true')
    print(f'  LoadableCPP     = "/Script/<YourModule>.{name}"   (NO F prefix)')
    print("Then: FCM->RegisterGun + RegisterPattern, or RequestUnboundGun. See SKILL.md workflow A/B.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
